name: Esegui gen.py ogni ora

on:
  schedule:
    - cron: '0 * * * *'  # Esegue ogni ora
  workflow_dispatch:  # Permette esecuzione manuale

permissions:
  contents: write  # Permette commit e push

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: pip install requests

      - name: Esegui lo script
        run: python gen.py

      - name: Verifica se sono stati generati file M3U8
        run: |
          if ls output_m3u8/*.m3u8 1> /dev/null 2>&1; then
            echo "File M3U8 trovati."
          else
            echo "Nessun file M3U8 generato. Esco."
            exit 0  # Esce senza fare commit o push
          fi

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Aggiungi e committa i file generati
        run: |
          git add output_m3u8/*.m3u8
          if git diff --cached --quiet; then
            echo "Nessun cambiamento da committare."
            exit 0
          fi
          git commit -m "Aggiornati file M3U8"

      - name: Pusha le modifiche
        run: git push