name: Esegui Gen.py ogni 30 minuti

on:
  schedule:
    - cron: '0 * * * *'  # Esegue ogni 30 minuti
  workflow_dispatch:  # Permette di eseguire manualmente

permissions:
  contents: write  # Permette di fare commit e push nel repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: pip install requests

      - name: Esegui lo script
        run: python def.py

      - name: Aggiungi il file generato al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Aggiungi file generato channels_italy"

      - name: Pusha il cambiamento
        run: git push
