name: Aggiorna Playlist M3U8

on:
  schedule:
    - cron: "*/30 * * * *"  # Esegue ogni 30 minuti
  workflow_dispatch:  # Permette di avviare il workflow manualmente

jobs:
  update_m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Usa il token segreto

      - name: 🔧 Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Installa le dipendenze
        run: pip install requests

      - name: 🚀 Esegui lo script per generare le playlist M3U8
        run: python script.py  # Assicurati che il tuo script sia chiamato `script.py`

      - name: 📂 Commit e Push dei file aggiornati
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add m3u_files/*.m3u8
          git commit -m "Aggiornamento automatico playlist M3U8 $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nessuna modifica da commitare"
          git push https://x-access-token:$GH_PAT@github.com/realbestia/worldm3u.git main
